version: 2.1
executors:
  docker-get:
    docker:
      - image: exgo/code-cadet-compiler:latest

jobs:
  build:
    executor: docker-get
    steps:
      - checkout
      - run:
          name: Setup google test repo
          command: |
            cd third_party
            git submodule init
            git submodule update
      - run:
          name: Setup cmake and build artifacts
          command: |
            make
      - persist_to_workspace:
          root: .
          paths:
            - out
            - benchmark_tests

  test:
    executor: docker-get
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd out
            ./tests --gtest_output=xml
      - store_test_results:
          path: out

  benchmark:
    executor: docker-get
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Benchmark
          command: |
            cd out
            ./benchmarks --benchmark_format=json > benchmark_test.json
            cd ../benchmark_tests
            node benchmark-format.js ../out/benchmark_test.json
            curl -u elastic:$ELASTIC_PASS -H "Content-Type: application/x-ndjson" -XPOST "https://e43e40cc22ec463395fae51bd5ffa5e0.eastus2.azure.elastic-cloud.com:9243/benchmark/_bulk?pretty" --data-binary "@output-benchmarks.json"
  merge:
    executor: docker-get
    steps:
      - checkout
      - run:
          name: Merge request
          command: |
            cd ./.circleci
            /bin/bash auto-merge.sh $CIRCLE_BRANCH $GITHUB_TOKEN

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - benchmark:
          context: elastic
          requires:
            - build
      - merge:
          context: github
          requires:
            - test
