version: 2.1
executors:
  docker-get:
    docker:
      - image: exgo/code-cadet-compiler:latest

jobs:
  build:
    executor: docker-get
    steps:
      - checkout
      - run:
          name: Setup google test repo
          command: |
            cd third_party
            git submodule init
            git submodule update
      - run:
          name: Setup cmake and build artifacts
          command: |
            make
      - persist_to_workspace:
          root: .
          paths:
            - out

  test:
    executor: docker-get
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute Tests
          command: |
            cd out
            ./tests --gtest_output=XML
      - store_test_results:
          path: out

workflows:
  build-master:
    jobs:
      - build
      - test:
          requires:
            - build
